apiVersion: v1
kind: Pod
metadata:
   name: logging-sidecar
   namespace: default
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: busybox1
    image: busybox
    command: ['sh', '-c', 'while true; do echo $RANDOM Logging data > /output/output.log; sleep 5; done']
    volumeMounts:
    - name: shared-data
      mountPath: /output

  - name: sidecar
    image: busybox
    command: ['sh', '-c', 'tail -f /input/output.log']
    volumeMounts:
    - name: shared-data
      mountPath: /input
